language: python
# command to install dependencies
python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check --diff.
  - flake8 .
  - coverage run --source=accessible_restaurant manage.py test

after_script:
  - coveralls
